name: "Godot CI Export"

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  export-windows:
    name: Windows Desktop Export
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build Directory
        run: mkdir -p build/windows

      - name: Godot Export (Windows)
        run: godot --headless --export-release "Windows Desktop" build/windows/NeoSukudo.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows
